string_from_file = """
// Aptop: ...
// Лицензия: ...
// Дата: ...
// Содержание: ...
"""
import itertools

for line in itertools.dropwhile(lambda line: line.startwith("//"), string_from_file.split("\n")):
    print(line)
